### ISSUE TITLE
Add example configuration to readme

### ISSUE THREAD

**Issue by mvdwetering** [MindFreeze/ha-sankey-chart#1]
**Is your feature request related to a problem? Please describe.**
I was playing around with this card and it took me some time before I got the configuration right.

**Describe the solution you'd like**
I think it would have helped there was an example to reference. For example the configuration of the card used to get the image in the readme. That way I could see the configuration and relate to how it looks in the picture.

**Describe alternatives you've considered**
I just kept trying and it worked out in the end

**Additional context**
Nothing else to add.

**Comment by MindFreeze** [comment]
Good idea. I'll add an example
