### ISSUE TITLE
Color based on entity state

### ISSUE THREAD

**Issue by amaximus** [MindFreeze/ha-sankey-chart#10]
**Is your feature request related to a problem? Please describe.**
Support for coloring entiies based on their state. This could be set on entity object level.

**Describe the solution you'd like**
I was thinking of creating a dependency graph (if possible, otherwise a tree) between the different entities.
E.g. heating in a room depends on the Zigbee temperature sensor that depends on the Zigbee-wifi bridge that depends on MQTT. Other sensors also depend on the zigbe-mqtt, etc.:
```
mqtt - device_tracker.zigbee_bridge - sensor.zb_temp ----- climate.heat
                                 \ \ sensor.zb_door_window /
                                  \ sensor.zb_water_leak
```
So if a device/entity in this dependency graph fails this card could be used to make it visible what other entities are affected. Most visibly the color based on state could do that.

**Describe alternatives you've considered**
none yet, I just found this card today.

**Additional context**

**Comment by MindFreeze** [comment]
I am not sure I completely understand your use case but dynamic color is a great idea in any case.

**Comment by amaximus** [comment]
Thanks for your quick reply and your work on the card.
For now I'm just experimenting with your card. 
For some reason some of the sensors are not displaying and other entity tpes (device_trackers, covers, switches, binary_sensors, input_booleans) don't display either: neither as branches nor as leaves. Is there any limitation to specific sensors only?

Once I figure it out and display them I'll show you the dependency graph/tree that I was thinking about (of course without the colors based on states).

**Comment by MindFreeze** [comment]
Only numeric state is supported and even then only positive values are displayed.

**Comment by amaximus** [comment]
Thanks for the clarification, you spared me a lot of time trying to figure out why specific entities do not show up.

Based on your comment, the dynamic color support could be based on 0 and non-0 values (that simplifies things).

It would be good to mention the conditions somewhere in the README.

**Comment by amaximus** [comment]
Promised you a use case:
![dependency_tree](https://user-images.githubusercontent.com/2511168/170527282-8bb1cb8f-037c-474f-873e-ed6a1f59369e.png)
