### ISSUE TITLE
Correct spelling of subtract in many places

### ISSUE THREAD

**Issue by AlexCPU** [MindFreeze/ha-sankey-chart#100]
I appreciate English isn't everyone's first language, so please don't take this the wrong way.
Could we get instances of "substract" corrected to "subtract" please?

I can submit a PR with a simple find+replace performed, but that would be a breaking change for peoples config, so if might be better to correct the spelling but keep supporting "substract_entities" for some time/forever, and I don't understand the code well enough to do that.

**Comment by MindFreeze** [comment]
Lol. I guess ai wrote it wrong once and copied it all over. Yea, it should be backwards compatible
