### ISSUE TITLE
Drilldown / Zoom

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [MindFreeze/ha-sankey-chart#104]
Another small feature addition I just considered.

Given my currently consolidated view- it gets pretty noisy. 

![image](https://user-images.githubusercontent.com/5262735/226133924-fb41163c-3f99-4060-8dc9-86cd1287751e.png)

It would be pretty useful, if say, I clicked on a node. Lets say, this one:

![image](https://user-images.githubusercontent.com/5262735/226133940-3f3e3b28-e5ca-4060-8022-8047d7f5ad76.png)

And, the dashboard filtered out everything except that node- like this:

![image](https://user-images.githubusercontent.com/5262735/226133966-a7cd6a76-3e49-4cc3-8300-4432f9a4e4cf.png)

And then, lets say, I wanted to zoom in more. So, I clicked on servers.

![image](https://user-images.githubusercontent.com/5262735/226133993-3ced97d1-943f-446d-b060-40fc8d0a76ca.png)

And, voila, it zooms in again.

![image](https://user-images.githubusercontent.com/5262735/226134040-38923e8a-9837-46ac-b7a2-7c7bebe4e23a.png)

And- of course, a reset zoom button somewhere to unfilter entities.

If such a feature were to come to light, I would imagine having a configuration to alter the behaviour of clicking on something.

click_action: zoom # Filters displayed entities to this one, and its children. Sets as top-level.
click_action: details # Opens home assistant details
click_action: service / button / action / etc.

**Comment by MindFreeze** [comment]
added in [1.15.0](https://github.com/MindFreeze/ha-sankey-chart/compare/v1.14.1...v1.15.0)

**Comment by XtremeOwnageDotCom** [comment]
Thanks, your great!
