### ISSUE TITLE
Feature Request: Allow users to specify an on click entity to open

### ISSUE THREAD

**Issue by sfstar** [MindFreeze/ha-sankey-chart#105]
**Is your feature request related to a problem? Please describe.**
I use the sankey chart for monitoring the current energy consumption of my home.
Often I find that I forgot to turn off a device behind a measuring socket with an built-in relay.
Currently I turn the device off by going to related, finding the relay entity and turning the relay to off.

**Describe the solution you'd like**
It would really help me/make it simpler if I could specify an on_click entity dialog to open when a specific entity in the chart is clicked.
This would be an optional configuration parameter that you can specifiy for the entity object to inform the sankey chart as to which entity you would like to open when an measuring entity is pressed.
The default behaviour would be to allow users not to specify the parameter and just open the measuring entity detail page.

**Describe alternatives you've considered**
I currently apply my work-around that involves multiple clicks to get to the relay.
Another solution would require the end-user to be able to customize the entity detail page but this will most likely be out of scope for this integration.

**Additional context**
None

**Comment by MindFreeze** [comment]
added `tap_action` for even more customization
