### ISSUE TITLE
Vertical layout

### ISSUE THREAD

**Issue by simenopsahl** [MindFreeze/ha-sankey-chart#109]
A vertical layout optimized for mobile devices would be nice.

An option to select the layout in the UI or YAML.
For example `layout: vertical` or `layout: horizontal` (default)

I tried to use card_mod and CSS, but I don't know of a way to get the desired result using just CSS

I made a mockup image

![sankey-vertical-black](https://user-images.githubusercontent.com/2676016/232846607-b06533c5-c1ce-4705-a85f-4914a04ff104.png)

[sankey-vertical.svg](https://user-images.githubusercontent.com/2676016/232846501-f0314985-f33d-45ad-bd3f-b5cd55d1aa55.svg)
[sankey-vertical-transparent.png](https://user-images.githubusercontent.com/2676016/232846783-f7fc2c4f-8a0a-4ccc-b4c8-1abfcde8f9dd.png)

**Comment by commentsonly** [comment]
@MindFreeze: sind you pointed this to me from another topic ..... yes indeed that would be nice, Good idea @simenopsahl asked for.
I could name a couple of cards which would benefit from being able to declare the orientation, not just sankey.
But it's one of the major ones for sure. Namehandling will be challenging fpr sure. Perhasp you should think of 2 layout declarations. One for the overall chart and another one for the names. Especially in the lower section it becomes tricky to use words with more but 3 chars in the end.

**Comment by simenopsahl** [comment]
Yes, it could become crowded depending on the text labels.
I made some edits.
One with vertical text, which might be the best solution.
[sankey-vertical-text](https://user-images.githubusercontent.com/2676016/233732165-51209d75-89c5-4eb2-b34d-6a467d70051b.svg)
One with the entity boxes and text staggered. This doesn't look quite right in my opinion, but it could be improved upon
[sankey-vertical-staggered](https://user-images.githubusercontent.com/2676016/233732353-dcdc7b72-2a40-4951-98d1-827cfb929029.svg)

**Comment by MindFreeze** [comment]
Vertical text - don't like it because we are trying to avoid rotating your phone.
Staggered - looks promising at first but not sure it is feasible at all.
45° - love it. Looks difficult to calculate dynamic size though. Will think about it

**Comment by MindFreeze** [comment]
Released in beta for now. I decided to keep the labels horizontal and shrinking for now. May change them in the future but don't have the time for that now. 'auto' layout logic may also need more work
