### ISSUE TITLE
readablility issue since highlighted (mouse_over) is differnt if leaving an entity or a connection

### ISSUE THREAD

**Issue by commentsonly** [MindFreeze/ha-sankey-chart#117]
Release 1.14.0
Last working: can't say
Browser/OS: chrome / windows 11

Got a problem with the readability of the entity names/values.
Not always but I think I found a reproducable way.

Got 2 sankeys in a vertical stack, unsure if that does matter.

If you hover with the mouse over an entity it gets highlighted, Aswell as all it's connections and the connected entities.
This leads to a poorer readability of the textual parts, but that's ok, since what one wanted is to the highlight all connected things.
Highlighting gets turned off once you move the mouse away from an entity object (normal behaviour I'd say)
But, if you move the mousepointer onto a connection while being highlighted and then move it out of the sankey chart the highlighting remains static.
From a code perspective I'd say the mouse_over = true gets turned into false when the pointer leaves an entity bar object while it remains true if the mousepointer leave  connection.

Forgive for te poor coloring I wantd to keep that animated gif as small as possible.
But you should see the difference between the pointer moving out of the chart from an entity vs. moving out of the chart from a connection.

![sankey_readability_issue](https://github.com/MindFreeze/ha-sankey-chart/assets/35866491/dcd428e0-3338-462c-9a4d-cefb77dbdc46)

**Comment by commentsonly** [comment]
Yes because some time in the past you recommended it to me to address a differnt problem which was that from time to time some entities were simply missing (not displayed at all). And yes throttle did nearly fix that issue.
Looks as if I must give it a try with smaller throttle values then.

**Comment by commentsonly** [comment]
throttle changed from 120 down to 12 ... seems to work

**Comment by MindFreeze** [comment]
The highlighting should ignore or restart the throttle I guess but seems like low priority
