### ISSUE TITLE
Currency instead of kWh

### ISSUE THREAD

**Issue by CrazyHenk44** [MindFreeze/ha-sankey-chart#120]
I'll keep it short: I would like to see the amount of money instead of the kWh. That way I can see how much money I've spent on energy in total and then split out further. Just like the energy dashboard does. 

My children (the imaginary ones unfortunately) do not have a clue about kWh's, but if they see the amount of money they can relate to it better.

**Comment by MindFreeze** [comment]
Sorry but it is out of scope. You can do this yourself. Find/create entities with with cost and configure the card to show them. This is what the configuration is for.
