### ISSUE TITLE
Energymix color gradation

### ISSUE THREAD

**Issue by JoeKae** [MindFreeze/ha-sankey-chart#122]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
We have the capability to apply colors to entities, and the corresponding chart will display these colors accordingly. However, i believe there is untapped potential in fully utilizing this feature. One exciting possibility is visualizing the energy mix by smoothly blending colors or stacking them in a rainbow pattern along the energy flow path. This enhancement could provide a more comprehensive and informative representation of the energy mix.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by MindFreeze** [comment]
I don't understand. This sounds like the way it already works. Can you share a picture of what you mean?

**Comment by JoeKae** [comment]
![example](https://github.com/MindFreeze/ha-sankey-chart/assets/52297861/8f2f7ee6-c562-4d7c-b278-3b9e8c2b77ac)
Take a look at the sample chart provided. The color applied to each entity is only extended to the immediate child level. However, the color does not propagate further to the subsequent children of those children.
Consequently, when observing "Floor 1" and its children, there is no clear indication of the energymix, as the color representation does not fully traverse the entire hierarchy of entities.

**Comment by MindFreeze** [comment]
I think I understand now. But that sounds very complicated to implement and this card already has too much complexity

**Comment by MindFreeze** [comment]
I am going to cancel this. The complexity would be high and mixing colors rarely leads to the desired results. There are very few color combinations that would yield a meaningful result when mixed
