### ISSUE TITLE
Autoconfig is not working 

### ISSUE THREAD

**Issue by MelleD** [MindFreeze/ha-sankey-chart#126]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Browser and Operating System:**

MacOS (Chrome, FireFox, Safari)
IOS App

**Description of problem:**

I tried the Autoconfig feature. I get an Entity Not Found error, but I can't see anything further, both in the console and elsewhere.

Any idea what I can test?

```
      - type: vertical-stack
        cards:
          - type: energy-date-selection
          - type: custom:sankey-chart
            autoconfig:
              print_yaml: true
```

<img width="1019" alt="Bildschirmfoto 2023-09-13 um 20 56 16" src="https://github.com/MindFreeze/ha-sankey-chart/assets/6340898/2cb992ca-15e8-4371-b08b-ef14270a309f">

<img width="490" alt="Bildschirmfoto 2023-09-13 um 20 55 09" src="https://github.com/MindFreeze/ha-sankey-chart/assets/6340898/97abd4e7-6572-4f3e-9530-5e92de918b56">

**Comment by MindFreeze** [comment]
`sections: []` suggests there is no energy data configured. Do you have entities configured in the HA energy dashboard?

**Comment by MelleD** [comment]
> `sections: []` suggests there is no energy data configured. Do you have entities configured in the HA energy dashboard?

Yes off course :)

<img width="832" alt="Bildschirmfoto 2023-09-14 um 07 50 45" src="https://github.com/MindFreeze/ha-sankey-chart/assets/6340898/420426ec-c86d-46be-8f0e-5652f38bb0fa">

**Comment by MindFreeze** [comment]
This is only consumption. Do you track production from solar/grid? Like this:
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/5219205/43534427-e761-4e60-992c-63d9f0b52a9b)

**Comment by MelleD** [comment]
Jip
<img width="369" alt="Bildschirmfoto 2023-09-14 um 09 30 57" src="https://github.com/MindFreeze/ha-sankey-chart/assets/6340898/5bdf428c-fe31-4890-a282-11968db01fa3">

**Comment by MelleD** [comment]
@MindFreeze Any idea what I can test?

**Comment by MindFreeze** [comment]
can try this in the dev console and share the output `JSON.stringify((await hassConnection).conn._energy.prefs.energy_sources)` ?

**Comment by MindFreeze** [comment]
Also check your energy dashboard configuration. I've seen this bug when someone had left an entity there that didn't exist anymore. The error msg should be improved at least but I haven't been able to reproduce this

**Comment by MelleD** [comment]
> Also check your energy dashboard configuration. I've seen this bug when someone had left an entity there that didn't exist anymore. The error msg should be improved at least but I haven't been able to reproduce this

I removed all sensor which are not available, but changed nothing. Let me check the output later.
Thanks

**Comment by MelleD** [comment]
> JSON.stringify((await hassConnection).conn._energy.prefs.energy_sources)
Output is:
`'[{"type":"grid","flow_from":[{"stat_energy_from":"sensor.smart_meter_63a_energy_real_consumed","stat_cost":null,"entity_energy_price":"sensor.solarnet_grid_import_tariff","number_energy_price":null}],"flow_to":[{"stat_energy_to":"sensor.smart_meter_63a_energy_real_produced","stat_compensation":null,"entity_energy_price":"sensor.solarnet_grid_export_tariff","number_energy_price":null}],"cost_adjustment_day":0},{"type":"solar","stat_energy_from":"sensor.symo_8_2_3_m_1_energy_total","config_entry_solar_forecast":["6cca214e7b5d43607ed098d4071eba83"]}]'`

**Comment by MindFreeze** [comment]
I can't reproduce this with existing entities. I added more specific logging in v1.14.1 . Try that and see if you get something new, especially in console

**Comment by matthewhadley** [comment]
I just started using this card and have the same error. I'm using v1.14.1 and don't see any console output or logging for any error.

**Comment by MelleD** [comment]
Hey @MindFreeze,

sorry for the late response (was on vacation :-) ). I tried the new Version:
i just see on the console:
`sankey-chart  Version 1.14.1 `

I see one error now on the issue tab (not sure if it is related)
`Content Security Policy of your site blocks the use of 'eval' in JavaScript``

On the console output I see no error:

```
JSON.stringify((await hassConnection).conn._energy.prefs.energy_sources)
'[{"type":"grid","flow_from":[{"stat_energy_from":"sensor.smart_meter_63a_energy_real_consumed","stat_cost":null,"entity_energy_price":"sensor.solarnet_grid_import_tariff","number_energy_price":null}],"flow_to":[{"stat_energy_to":"sensor.smart_meter_63a_energy_real_produced","stat_compensation":null,"entity_energy_price":"sensor.solarnet_grid_export_tariff","number_energy_price":null}],"cost_adjustment_day":0},{"type":"solar","stat_energy_from":"sensor.symo_8_2_3_m_1_energy_total","config_entry_solar_forecast":["xxx"]}]'
```

**Comment by MindFreeze** [comment]
I found 1 more place where an error might not be logged to the console and added logging in v1.15.0 . Write back if you get an error in the console with that one, pls

**Comment by MelleD** [comment]
<img width="1015" alt="Bildschirmfoto 2023-10-01 um 20 59 05" src="https://github.com/MindFreeze/ha-sankey-chart/assets/6340898/cdaaeac9-dfcf-405e-af4d-cfb0263cf08c">

But I cannot see which Entity

**Comment by matthewhadley** [comment]
Using some breakpoints I was able to see the errors come after calls made to the homeassistant websocket `config/entity_registry/get`, happening here: https://github.com/MindFreeze/ha-sankey-chart/blob/62bce10441bc0061acb47e365bc3619e2cbbbe5c/src/hass.ts#L42.
On a hunch I deleted an entry from my energy dashboard and once I deleted it the autoconfig worked.

The origin of that entry is a template sensor:

```
- name: Pool Filter Pump Energy Metering
  icon: mdi:lightning-bolt
  unit_of_measurement: W
  device_class: power
  state: >
    {% if is_state('sensor.pool_filter_pump_speed', 'low') %}
    485
    {% elif is_state('sensor.pool_filter_pump_speed', 'medium') %}
    690
    {% elif is_state('sensor.pool_filter_pump_speed', 'high') %}
    1160
    {% else %}
    0
    {% endif %}
```

Perhaps this kind of sensor doesn't have an entity and so causes the error?

**Comment by MelleD** [comment]
Hey @MindFreeze,

I've also gone a step further and found the 2 "critical" sensors that lead to problems:

Sensor 1 from powercalc integration:
<img width="1027" alt="Bildschirmfoto 2023-10-02 um 22 40 52" src="https://github.com/MindFreeze/ha-sankey-chart/assets/6340898/e08c5027-8f15-454c-b7af-39ce111b7e2a">

Sensor 2 is a group sensor:

<img width="1172" alt="Bildschirmfoto 2023-10-02 um 22 50 26" src="https://github.com/MindFreeze/ha-sankey-chart/assets/6340898/c55e1779-3c8b-41b4-8e7b-6dcfffa88a88">


After that I see:

<img width="492" alt="Bildschirmfoto 2023-10-02 um 22 52 00" src="https://github.com/MindFreeze/ha-sankey-chart/assets/6340898/bcf98a8d-6b8a-47c8-8037-27f9a054852d">

**Comment by MelleD** [comment]
Hey @MindFreeze,

One more question. The Energy Dashboard currently calculates the grid consumption independently without using a sensor. Do this function also exists? Because this information is now missing in the chat.

**Comment by MindFreeze** [comment]
No, missing grid consumption will not be created by autoconfig, but you take the yaml output, disable `autoconfig` and add it manually as a `type: remaining_child_state`

**Comment by MindFreeze** [comment]
No idea why but this error seems to come from the call for entity area. I made it default to 'no area' in this case so it should be "fixed" in v1.15.1

**Comment by MelleD** [comment]
> No, missing grid consumption will not be created by autoconfig, but you take the yaml output, disable `autoconfig` and add it manually as a `type: remaining_child_state`

Ok, yes this is working and looks good so far. Thanks

**Comment by MelleD** [comment]
> No idea why but this error seems to come from the call for entity area. I made it default to 'no area' in this case so it should be "fixed" in v1.15.1

Ok I can test it :)

**Comment by matthewhadley** [comment]
`v1.15.1` is working for me!

**Comment by MelleD** [comment]
Jip for me too

**Comment by matthewhadley** [comment]
While the card is rendering properly now, I do see an error in console:

```
[Error] {code: "not_found", message: "Entity not found"}
	(anonymous function) (ha-sankey-chart.js:1:52231)
```

**Comment by MindFreeze** [comment]
> While the card is rendering properly now, I do see an error in console:
> 
> ```
> [Error] {code: "not_found", message: "Entity not found"}
> 	(anonymous function) (ha-sankey-chart.js:1:52231)
> ```

Yes, the error is still there. I hope to find out why it happens if I can reproduce it someday.

**Comment by matthewhadley** [comment]
> Yes, the error is still there. I hope to find out why it happens if I can reproduce it someday.

Hopefully creating a sensor that's similar to the one in https://github.com/MindFreeze/ha-sankey-chart/issues/126#issuecomment-1742363127 should allow you to reproduce as it's all template based.

**Comment by MelleD** [comment]
> > While the card is rendering properly now, I do see an error in console:
> > ```
> > [Error] {code: "not_found", message: "Entity not found"}
> > 	(anonymous function) (ha-sankey-chart.js:1:52231)
> > ```
> 
> Yes, the error is still there. I hope to find out why it happens if I can reproduce it someday.

Should I share my sensor(s)? I think it’s easy to reproduce…

**Comment by MindFreeze** [comment]
> > > While the card is rendering properly now, I do see an error in console:
> > > ```
> > > [Error] {code: "not_found", message: "Entity not found"}
> > > 	(anonymous function) (ha-sankey-chart.js:1:52231)
> > > ```
> > 
> > 
> > Yes, the error is still there. I hope to find out why it happens if I can reproduce it someday.
> 
> Should I share my sensor(s)? I think it’s easy to reproduce…

Sure

**Comment by MelleD** [comment]
For sensor 1. It's just a daily fixed powercalc sensor

```
powercalc:
  sensors:
  - name: wash
    daily_fixed_energy:
      value: 0.01
```
https://homeassistant-powercalc.readthedocs.io/en/latest/sensor-types/daily-energy.html

For sensor 2 it's sum group.
```
platform: group
name: Group Energy
type: sum
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
entities:
  - sensor.energy1
  - sensor.energy2
```
