### ISSUE TITLE
Padding and show_icons

### ISSUE THREAD

**Issue by emufan** [MindFreeze/ha-sankey-chart#13]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

latest

**Last working release (if known):**

1. If you set show_icons: false it shows false instead of no icons.

![image](https://user-images.githubusercontent.com/22775515/169827437-8924caf3-c28c-4e68-afe5-6946f4d66182.png)

2. Can you perhaps set the padding around the container and not around the ha-card and set it to the standard padding 16px instead of 12px?

![image](https://user-images.githubusercontent.com/22775515/169826207-a454e0cd-f3f9-48ce-b33c-e46e3fda9bb1.png)

![image](https://user-images.githubusercontent.com/22775515/169826364-418e7e0d-53b6-4fd8-948a-65cef7c9c5d7.png)

Currently, the padding differs to other standard cards (see above) and as you are using standard h1, it is currently added again, which differs even more.

![image](https://user-images.githubusercontent.com/22775515/169826612-25ba4d0c-0e8a-4200-8397-98ffa77df11d.png)
![image](https://user-images.githubusercontent.com/22775515/169826745-28958f93-669d-452a-b5f4-d220d73ac44f.png)

Of yourse, I can set this all via card_mod, but prefer to have the HA standard natvie in cards and only change it, if I want to see it different. And the standard is 16 px below header (instead of 12) and header has its own separate padding.

**Comment by emufan** [comment]
Currently this is my work-around

```
    ha-card {
      padding: 0px !important;
    }
    .container {
      padding: 0px 16px 16px 16px !important;
    }
```

**Comment by MindFreeze** [comment]
fixed in v0.6.3

**Comment by emufan** [comment]
@MindFreeze Top. But I saw, that unset width or set it to auto or initial is important to not have it outside the right border.

```
    .container {
      padding: 0px 16px 16px 16px !important;
      width: auto !important;
    }
```

![image](https://user-images.githubusercontent.com/22775515/170306099-7e0f09a3-2aae-4fa4-90d8-5b3183391031.png)

**Comment by MindFreeze** [comment]
I don't have this problem but the `width: 100%` seems entirely unnecessary so I'll remove it in the next version
