### ISSUE TITLE
Sort with group by?

### ISSUE THREAD

**Issue by KidA001** [MindFreeze/ha-sankey-chart#135]
**Is your feature request related to a problem? Please describe.**
I'm using the sort feature and though I do want to sort, it makes it difficult to understand when the lines from a previous parent cross with another. See my screenshot below. 
<img width="1153" alt="image" src="https://github.com/MindFreeze/ha-sankey-chart/assets/8673088/218c829d-b7d4-4936-ae7a-0cf9fd94ec76">

**Describe the solution you'd like**
It would be great if there was a way to sort and group by the previous parent. For instance in my screenshot above I'd like to sort the Main House and Studio/Garage respectively, so that the lines from the children don't cross.

**Describe alternatives you've considered**
Maybe there is already a way to do this that I'm not familiar with. Thanks for your work, this is an awesome tool

**Comment by MindFreeze** [comment]
Skip the `group_by_parent` option and let's make this the default behavior. The issue is that parents may also be sorted and that sorting isn't saved yet.
So first `this.sections = filteredConfig.sections.map(...)` has to be refactored to a forEach loop of `filteredConfig.sections` that assigns to `this.sections[i]` at each loop.
This way when we call `this._sortBoxes` we can pass `this.sections[i-1]` which is the sorted parent boxes and they contain `children` info, so we can sort by parent first and then by state

**Comment by MindFreeze** [comment]
@KidA001 I found it easier to just implement it. It will be part of 1.16.0

**Comment by KidA001** [comment]
Hah, I was going to say it sounds like you know exactly what to do. These HA plugins often get hoarded with feature requests so I try to offer my support when I'm making one myself. Thanks for working on this!

**Comment by nathan-curtis** [comment]
@MindFreeze how do I turn this off? It's completely jacked all my charts - I sort by entity value asc - and its not working correctly.

**Comment by nathan-curtis** [comment]
> Skip the `group_by_parent` option and let's make this the default behavior. The issue is that parents may also be sorted and that sorting isn't saved yet. So first `this.sections = filteredConfig.sections.map(...)` has to be refactored to a forEach loop of `filteredConfig.sections` that assigns to `this.sections[i]` at each loop. This way when we call `this._sortBoxes` we can pass `this.sections[i-1]` which is the sorted parent boxes and they contain `children` info, so we can sort by parent first and then by state

This is my breaking change, sir, and a regression as not listed as breaking.  Please revert. or provide override.

**Comment by kzajac83** [comment]
Hi All.

I’ve tried many different configurations, but none of them prevent the crossing. Any configuration, with or without `sort_group_by_parent`, gives me the same view. Could someone please explain how to use the card properly, or add a working example to the main page?

<img width="1495" height="911" alt="Image" src="https://github.com/user-attachments/assets/638d4f58-8f07-4d04-8559-3468070418de" />

My code is here: 

[PEC_Sankey.txt](https://github.com/user-attachments/files/22706711/PEC_Sankey.txt)

**Comment by MindFreeze** [comment]
It's probably because of the passthrough. Might be a bug

**Comment by kzajac83** [comment]
Can be. Should I create a new ticket, or is it better to continue this one (maybe it's possible to reopen it)?

By the way, I assigned a name to "passthrough" to see the value, but nothing was displayed. Not sure if that’s by design or if it’s a bug as well?

BR, Krzysiek
