### ISSUE TITLE
Prefix/space + font size

### ISSUE THREAD

**Issue by emufan** [MindFreeze/ha-sankey-chart#14]
Would be great to set a real prefix in front of the unit. I would like to set a blank, because for me it is hard to read, if the unit is directly after the number.

And it would be great if I can set the font size of the descriptions as well. Same for font-color and font-decoration. I would like to unset italic, but have it e.g. in grey and smaller. 😎

**Comment by MindFreeze** [comment]
I'll start by adding a separate span for the unit and some classes so you can use card mod. Might add a full style property for labels later.

**Comment by emufan** [comment]
👍 Fair. For me an addressable span is enough, because card_mod already in place for other settings.

**Comment by MindFreeze** [comment]
spans added in v0.6.2

**Comment by MindFreeze** [comment]
I think stuff like this should be handled with card-mod like you are doing, so I will close this and simplify my life.

Note that the font-size for `div.label` is set dynamically, so use `em` units instead of `px` when adjusting it for the spans.

**Comment by emufan** [comment]
@MindFreeze Already up and running. Thx a lot.

**Comment by klaus1k** [comment]
> @MindFreeze Already up and running. Thx a lot.

Could you share the configuration of card mod for the added space?
Thanks in advance!

**Comment by emufan** [comment]
```
card_mod:
  style: |
    .unit {
      padding-left: 3px;
    }
```

**Comment by klaus1k** [comment]
Awesome, thanks a lot! Looks perfect now.
