### ISSUE TITLE
1.16 breaks scaling between card sections

### ISSUE THREAD

**Issue by nathan-curtis** [MindFreeze/ha-sankey-chart#142]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:**
1.16.x
**Last working release (if known):**
1.15.x
**Browser and Operating System:**
Win11 Moment 4, Edge 118.0.2088.46 (Official build) (64-bit)

ALL
**Description of problem:**
Scaling off segments between sections changed between versions - Please revert to 1.15 scaling behavior or provide override option

This picture is 'correct' taken in 1.15.1
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/24819138/1c6d8aa5-1d79-4517-b241-d5ab65d4646f)

This is in 1.16.1 (1.16.0 also shows inconsistent bar scaling as well)
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/24819138/b28acd09-414b-45af-afec-fb124f655fb7)

**Comment by nathan-curtis** [comment]
Not fixed in 1.17:
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/24819138/5e256f17-308c-4337-9660-cf559744ec0b)

Specifically look at section 5, second item - IT Closet  Trace that back one step - What the heck is going on there? why are the lobes changing size?  I expect that bar once it breaks off - to maintain relative width  0.97KwH should be represented as the same amount relative to the unit - not relative to the percent visible on a 100% bar

It looks like you're trying to scale the window to 100% top/bottom for each - NO stack the energy values based on the smallest unit displayed and the chart height is the chart height  please see the first.

**Comment by MindFreeze** [comment]
Ah, I think I see where the problem is. Will fix in next version

**Comment by nathan-curtis** [comment]
fixed in 1.17.1:
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/24819138/82af4255-2475-49f7-acfd-95d76c36deff)
