### ISSUE TITLE
Use static relative start / end dates instead of using energy-date-selector

### ISSUE THREAD

**Issue by widewing** [MindFreeze/ha-sankey-chart#151]
**Is your feature request related to a problem? Please describe.**
Currently this plugin cannot show multiple charts of different dates in one dashboard. For example it's impossible to show today/yesterday/this week/last week data in one dashboard. 

Additionally it cannot show more precise data than a day. Some time it's useful to know the energy usage of last hour or last few minutes.

**Describe the solution you'd like**
Add parameters like "start_date" / "end_date" to the chart. it can use relative annotation. I really like the Grafana's implementation: e.g. "-1d", "-1w/w"
refer: https://grafana.com/docs/grafana/latest/dashboards/use-dashboards/?pg=blog&plcmt=body-txt#set-dashboard-time-range

**Describe alternatives you've considered**
Predefined list of date ranges

**Additional context**
N/A

**Comment by MindFreeze** [comment]
[v3.3.0](https://github.com/MindFreeze/ha-sankey-chart/releases/tag/v3.3.0)

**Comment by blacknell** [comment]
Fantastic - thank you
