### ISSUE TITLE
challenges with the Sankey Chart Card.

### ISSUE THREAD

**Issue by ojm88** [MindFreeze/ha-sankey-chart#155]
Hello.

I have challenges with the Sankey Chart Card. Sankey looks like in the picture when HA is updated or restarted?

Can you help me with this problem?

Greetings, Ole Jørgen.
![IMG_6908](https://github.com/MindFreeze/ha-sankey-chart/assets/149431970/dd658a9a-3fc5-4a92-8bf2-d9e1da7c7188)

**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by MindFreeze** [comment]
Looks like something in HA isn't loaded yet. Maybe a template sensor. I don't see how the card itself can cause this.
Does it get better after HA is fully started?
