### ISSUE TITLE
Sort_by for autoconfig

### ISSUE THREAD

**Issue by matellis** [MindFreeze/ha-sankey-chart#157]
**Is your feature request related to a problem? Please describe.**
The autoconfig feature is tremendous; it would be even better if one could sort within each section without having to explicitly list the entities.

**Describe the solution you'd like**
A sort_by parameter that affects the contents of all sections the same way. Sort_by value would be fine for me.

**Describe alternatives you've considered**
I could print the YAML and add sort_by to each section, but that would need to be maintained when I make any changes to the Panel in the future. I tried adding sort_by in the configuration, including inside the `sections: []` area, with no effect.

**Additional context**
Here's a pic of the autogenerated Sankey chart I've with no sorting by default.

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/138857/fb54c79e-0ae3-4f09-95a0-1c56a4f3cb37)

**Comment by MindFreeze** [comment]
@Montreal666 Probably a cache issue. The config looks ok. I will add the options to the ui in the next release

**Comment by Montreal666** [comment]
It was indeed a cache issue, thank you.
however the sorting is done globally for all sections (using autoconfig); is it possible to sort within each section?

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/56667580/5cb246da-946e-4f55-b3b4-df1fd9915fca)

Thx

**Comment by MindFreeze** [comment]
@Montreal666 this is exactly what was requested. Sorting can be set per section but only with manual sections

**Comment by Montreal666** [comment]
Thank you, no problem.
will consider manual sections.
Cheers,
