### ISSUE TITLE
Convert energy to CO2 or $

### ISSUE THREAD

**Issue by madsciencetist** [MindFreeze/ha-sankey-chart#158]
More in depth than #54, I’d like to display my energy consumption, including both electricity and fossil fuel. Specifically, I’d like a sankey in which a column has three entries: low-carbon electricity, fossil electricity, and natural gas. Or perhaps the first column has “clean energy” and “fossil energy” which redistribute into “electricity” and “gas” in the second column. Either way, my dozens of electricity-monitoring entities would feed from there.

While kJ could be used as a common unit, I am more interested in two other common units: dollars, using the same price of energy that the Energy Dashboard does, and CO2eq, using the same CO2/kWh carbon intensity that the Energy Dashboard does.

The result would be that I can set the energy time duration to the last month and see the cost and carbon intensity of every entity - including both my heat pump and gas furnace.

**Comment by madsciencetist** [comment]
I think the right way to do this - with the ability to correctly account for varying carbon intensity and TOU rates - is to add attributes to the energy sensors, so that when [an increment of] energy is logged, the corresponding [increment of] CO2 and money are logged as well, using the rates at that time.

It just so happens that my electric rates and carbon intensity are relatively flat though, so just having the sankey chart scale all the numbers by a fixed config value will be a lot easier.

**Comment by madsciencetist** [comment]
Got it working:
![image](https://github.com/MindFreeze/ha-sankey-chart/assets/7854563/44e7a56d-b939-49e7-9128-52a1a849ca77)

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/7854563/8770f092-7fb0-4799-9a10-ef1085fc4f2d)

@MindFreeze before I spend time cleaning up the code to PR - is this a feature you are interested in integrating?

**Comment by MindFreeze** [comment]
Sure. As long as any computations are skipped by default and only done when enabled by the config
