### ISSUE TITLE
Invalid entity config on autoconfig

### ISSUE THREAD

**Issue by kernel610** [MindFreeze/ha-sankey-chart#163]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
Home Assistant Core: 2024.2.2
ha-sankey-chart: v1.20.0

**Last working release (if known):**
I don't know exact version but it was working a few weeks ago.

**Browser and Operating System:**
Chrome
MacOS Sonoma 14.3

**Description of problem:**
The card renders as an error when using autoconfig. I've tried removing all entities from the Energy Dashboard one-by-one and still receive the error after refreshing the card.

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/75233032/bc428dac-9b32-4885-b131-4fdd822e6641)

If I set energy_date_selection: false, the dashboard renders blank despite entities with values still configured.

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/75233032/3c5b71f8-d981-42b2-8c7c-b832a72c1acb)

I can get it to render with just one section and a few entities but that doesn't make sense for the purpose of the sankey chart.

I'm guessing the error is in the starting section but can't seem to get anything to work.

**Comment by MindFreeze** [comment]
It looks like you don't have any energy sources configured, like grid, solar. This case isn't covered. If you don't have a real sensor for that, you can create a sum helper sensor from your consumer devices and use that for now.

**Comment by MindFreeze** [comment]
@kernel610 Please try v1.20.1 . It should work even without energy sources

**Comment by kernel610** [comment]
Confirmed this is fixed in v1.20.1. Thanks for the quick fix!
