### ISSUE TITLE
Line not drawn between parent and child.

### ISSUE THREAD

**Issue by gheydon** [MindFreeze/ha-sankey-chart#174]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

<img width="617" alt="image" src="https://github.com/MindFreeze/ha-sankey-chart/assets/70891/cec18178-2ade-484c-b433-43ce5e64c1b8">

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

<img width="754" alt="image" src="https://github.com/MindFreeze/ha-sankey-chart/assets/70891/950c401a-8632-4244-926b-9ada5d4668f7">

In my configuration of my chart the line from the Office to the 3d printer is not drawn. The office parent is a Group helper with several other items summed together.

When this broke and the line stopped showing, I was renaming the 3d printer power entity, and I updated everything so there was no reference to the old id and this started happening.

I have now been able to resolve this issue and the line draws correctly. It seems that in the Group I forgot to change the entity id for the 3d printer. I discovered this because the UOM was undefined, and when I corrected this the line started drawing again.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by MindFreeze** [comment]
So if I understand correctly, there is no bug here. Your entity was just misconfigured. 228W + 247W = 475W, so the 1W was just not there.
You can also do this in the card without a group entity btw. See `type: remaining_child_state`

**Comment by gheydon** [comment]
Thanks for clearing this up. I have been bashing my head against this for weeks and was 99% sure it was a config issue on my side and I was pretty really happy to have been able to resolve it.

I was mainly wanting to get this documented so anyone coming across a similar issue will be able to have some clue to what is going on.

Thanks.

**Comment by MindFreeze** [comment]
I hope to have this explained and documented better once I tackle #37
