### ISSUE TITLE
Connections are somehow randomly drawn

### ISSUE THREAD

**Issue by emufan** [MindFreeze/ha-sankey-chart#18]
I'm not sure, if it is a bug or working as designed, but the connections are somehow with random high on target side

![image](https://user-images.githubusercontent.com/22775515/170494306-93f92f24-2708-43de-a5d3-e2399fb12acd.png)

Some are too thin, some not there in total and it seems, that it is thinner and thinner per section from top to bottom. (each color is here a group of child's from entities before.

**Comment by MindFreeze** [comment]
Can you include at least the previous section in the screen shot? Set show_names to false if you are worried about privacy.

**Comment by emufan** [comment]
Sure.

![image](https://user-images.githubusercontent.com/22775515/170540448-005f3768-9dad-4ad7-b8ca-e52133fdd970.png)

BTW Possible to have (with k präfix) a Thousand delimiter (here in Germany .)? So 13.947 instead of 13947?

**Comment by MindFreeze** [comment]
For 13.947 you want to set `unit_prefix` to k and `round` to 3

This is screenshot is very strange. I will have to experiment a bit to figure it out. 
I am guessing that some of your sensors report fractions and get rounded down to 0. This is a bug as zeros shouldn't be displayed but rounding probably happens too late.

**Comment by emufan** [comment]
As said, "without k prefix" 😉 Because otherwise, the next column and all other values in the same column will show 0,239 instead of 239, But not that important. As is it only the ony value, I only thought, it is more common to have this thousands separator. But of course not urgent.

Same for the strange connectors. Not urgent.

**Comment by emufan** [comment]
With e.g. round:5 it looks the same

![image](https://user-images.githubusercontent.com/22775515/170547233-e7ec02a0-4e77-4634-b976-e3fc0467843e.png)

**Comment by emufan** [comment]
Here an updated one with differne colors, to see the cild sections better.

```
min_box_height: 8
min_box_distance: 8
wide: false
round: 5
height: 400
```

![image](https://user-images.githubusercontent.com/22775515/170673859-e6e67c81-4e90-46dd-8ca5-6cc965ca9c60.png)

The lower, the thinner. Regardless of values. Only the last child-section is braking this "rule" and makes it even different.

**Comment by emufan** [comment]
Did you already have some time to look into this? Whatever I try, it is the same. 


Some are too thin, some not there in total and it seems, that it is thinner and thinner (and sometimes not even there) per section from top to bottom. (each color is here a group of child's from entities before.

![image](https://user-images.githubusercontent.com/22775515/175270508-b795deaf-5546-46a6-8fd6-38c7e328ac9a.png)

or

![image](https://user-images.githubusercontent.com/22775515/175270652-d5d05d58-c4e0-40b9-8f14-62a245e33490.png)

Perhaps only a wrong rounding in calculation of the positions?

And what I saw now a lot of times as well. Above you can see that the vertical space is e.g. filled 90% in column 1. But sometimes it is only 40%, 20% or less. Why is this happening and how to avoid this?

![image](https://user-images.githubusercontent.com/22775515/175271084-c45a2832-72d7-44cf-a956-95b96283cd4f.png)

**Comment by MindFreeze** [comment]
This is all because you have a lot of tiny values in the last column. This requires a lot of empty space between the boxes and makes the pixels per state value weird. As I said 0 values should be hidden but I haven't had time to fix that. You can improve this a bit by reducing min_box_height and /or min_box_distance

**Comment by emufan** [comment]
No, As said, the 0 is only rounded 0,x. There is value. And these values should stay, because there is something >0 and therefor important to see.

And the mentioned problems are there if I remove the 0 values.

![image](https://user-images.githubusercontent.com/22775515/175775053-66c0be7f-912f-42b5-8b18-30a7f0fb27db.png)

A little bit less visible, but same.

1. There is something wrong in the connection line codes  From top to bottom the connections are thinner and thinner or are completely not there. Good to see in all the pictures. Good to see here
![image](https://user-images.githubusercontent.com/22775515/175774851-5d4462d1-1d74-4ef6-9606-e173a12e03ff.png)
and here
![image](https://user-images.githubusercontent.com/22775515/175774861-34b01503-afae-4515-affe-269b0bbc22ea.png)

2. The problem that the height of the first column is getting lower and lower, if the values invcrease over the day is still there as well.
![image](https://user-images.githubusercontent.com/22775515/175774901-60aa5c4c-83eb-451a-a07d-f579312b2639.png)
~half of the height some hours later
![image](https://user-images.githubusercontent.com/22775515/175774910-c8ce4fdf-50d5-4a6f-a9a1-4dfe2b02077d.png)
and in the evening again 20% of it.

**Comment by emufan** [comment]
Update. If I replace

```
l>0&&(i+=o)
```

with 

```
l==1000&&(i+=o)
```

correlated to

```
        if (endSize > 0) {
          // only increment if this connection will be rendered
          startYOffset += startSize;
        }
```

the end is fine. Completely. As said. A glith in code not values.

![image](https://user-images.githubusercontent.com/22775515/175777544-718dbcc9-ee3f-47ee-9ce2-dd64ff53baa8.png)

Unfortunately the startSize is worong then, but most probably only because of the compressed js.

**Comment by emufan** [comment]
And the 1% problem is as far as I can see, because of the max 1 in startsize calculation, to the heigh is too height in thos edge cases because of this. Without it it is fine

![image](https://user-images.githubusercontent.com/22775515/175804479-78b7c4ed-e2a1-4fe3-9277-70e04b35f1d8.png)

So instead

```
        const startSize = Math.max(Math.min(remainingEndState / b.state * b.size, b.size - startYOffset), 1);
```

now (if there is another background and to have still a lower limit.

```
        const startSize = Math.max(Math.min(remainingEndState / b.state * b.size, b.size - startYOffset), 0.1);
```

or directly

```
        const startSize = Math.min(remainingEndState / b.state * b.size, b.size - startYOffset);
```

**Comment by MindFreeze** [comment]
Your main issue is with rounding. There should never be a 0 value connected to anything. Yes, it may 0.1 underneath but this is meaningless if the UI shows 0. These 0 values will disappear in the next release so you may as well set `round: 1` now if you want to keep them.

**Comment by emufan** [comment]
No, the main issue are the corrections above. As said, even with removing the <0,5 values the problems are there. See above pictures. 

And to remove the values now, please only with an option. I really like to see them (that there is someting <1, but of course don't want to see ,x everywhere.

**Comment by MindFreeze** [comment]
fixed in v0.7.0

**Comment by emufan** [comment]
@MindFreeze With 0.7.0 a lot better, but still

![image](https://user-images.githubusercontent.com/22775515/177046347-998b748c-a2fc-4bac-9a0a-bd0506d5688f.png)

With my fix before:

![image](https://user-images.githubusercontent.com/22775515/177046406-7228c8de-8d35-4ce0-b443-20a8f985246d.png)

**Comment by emufan** [comment]
You are right. Thanks for pointing me ar this. Copy&Paste issue, here missing one daily->yearly replace in the sum helper sensor.
