### ISSUE TITLE
Can't copy "auto generated config yaml"

### ISSUE THREAD

**Issue by JokerGermany** [MindFreeze/ha-sankey-chart#182]
When I use the Option "Print auto generated config yaml" the code is shown, but i can not mark it fast enough, because sankey is relaoding (js?) to fast and the marked code is unmarked.

Is there a other way to get the code?

**Comment by icefest** [comment]
Change the throttle value?

**Comment by JokerGermany** [comment]
Nope, don't work =(

**Comment by JokerGermany** [comment]
got it via the source code, but i don't think that should be the way...

**Comment by MindFreeze** [comment]
> got it via the source code, but i don't think that should be the way...

You're right. I just keep forgetting to fix that. So let's keep this issue open
