### ISSUE TITLE
Option to Hide Unit of Measurement

### ISSUE THREAD

**Issue by woodmj74** [MindFreeze/ha-sankey-chart#19]
_**Is your feature request related to a problem? Please describe.**_
I don't believe this is currently supported. It would be awesome if you could chose to supress the display of the unit of measurement label. 

Currently....
> [value] [unit of measurement] [entity name] e.g. 10W Light

becomes...
> [value] [entity name] e.g. 10 Light

My rationale for this is two fold:

1. All the same unit; if I'm displaying things of the same type they all have the same units, therefore I'm happy to know what the unit is and don't need to display it on each entity
_For example, I've got 40+ zigbee devices and want to use their link quality, don't see why I need to repeat the words "link quality" on each line_
2. I've got mixed descriptions of unit but are essentially the same thing so displaying the unit of measurement can be confusing
_For example, the PiHole integration provides entities dns cached (expressed as "queries"), dns forwarded (expressed as "queries") and blocked (expressed as "ads") - these sum to the of total dns queries (expressed as "queries"). So I have unit of measurements of queries and ads representing the same thing_

_**Describe the solution you'd like**_
A new option in the configuration of:
**Name** hide_unit
**Type** boolean
**Requirement** Optional
**Default** false
**Description** Hide the units of measurements

_**Describe alternatives you've considered**_
I could create template sensors to replicate those I wish to display without a unit of measurement. This obviously increases the maintenance and number of sensors etc. etc.

**Additional context**

**Comment by MindFreeze** [comment]
Makes sense. As a workaround, you can use card-mod to hide it with css

**Comment by MindFreeze** [comment]
added in v0.8.0
