### ISSUE TITLE
Is possible to change COLOR in if else condition?

### ISSUE THREAD

**Issue by hammondb4** [MindFreeze/ha-sankey-chart#20]
I want to change colour of entity depending on condition.
For example:
      - entity_id: sensor.power_fv2grid
        name: FV to Grid
        color: >-
           {% if (states('sensor.power_fv2grid')|float > 0) %} green 
           {% else  %} red 
           {% endif %}
        children:
          - sensor.power_house

Tried this code, no errors, but not working.
Any suggestions?

**Comment by MindFreeze** [comment]
Templates are not supported in any cards AFAIK.

However you can achieve what you want with the new functionality in v0.6.4 . See #10
