### ISSUE TITLE
Order parent connections by parent entity position

### ISSUE THREAD

**Issue by madsciencetist** [MindFreeze/ha-sankey-chart#201]
It seems like connections are sorted by child order on the right but not by parent order on the left. Is there a way to prevent these connections from crossing, without changing entity order?

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/7854563/c2bd7bbb-f9bb-4d46-ab09-d8efa271f22a)

**Comment by MindFreeze** [comment]
Currently, no. I have to add sorting of the connections before their coordinates are calculated.

**Comment by MindFreeze** [comment]
@madsciencetist After staring at the code for a while, I can't figure out how this could happen. Connections are rendered from top to bottom and left to right.
Can you help me reproduce it with some minimal config?

**Comment by MindFreeze** [comment]
Since I can't reproduce this anymore, I'm going to assume it is fixed and close it

**Comment by madsciencetist** [comment]
Ah sorry, forgot about your repro request. This is not a problem for me
right now and if it becomes one again I’ll reopen with a repro config.
