### ISSUE TITLE
Appearance: Some margins perhaps needed

### ISSUE THREAD

**Issue by Floppe** [MindFreeze/ha-sankey-chart#202]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Chrome 125, Windows 11

**Description of problem:**
First child element not so visible if it's height is small.

![image](https://github.com/MindFreeze/ha-sankey-chart/assets/238729/91180128-3a95-4edf-a91e-273b5b10ea0e)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by MindFreeze** [comment]
This must be your custom CSS. The `.container` element normally has `padding: 16px`

**Comment by Floppe** [comment]
Could be, but I don't recall setting that anywhere and cannot find it either. I think this happened recently, several months since I did the CSS.

Fixed it for myself by adding in card-mod: 
`.container.with-header { padding-top: 6px !important; }`

otherwise it's 0.

If no others are affected, then perhaps close this issue. Thanks again for a great component!

**Comment by MindFreeze** [comment]
My bad. Found the issue and it is not your CSS :)
