### ISSUE TITLE
Mobile View is rrotated by 90° clockwise

### ISSUE THREAD

**Issue by HQOFIQ** [MindFreeze/ha-sankey-chart#206]
Sankey Chart Card on Home Assistant works great on desktop browser view - but when opening the very same on my mobile - no matter if directly in mobile browser or the native HA app - it always will be displayed 90° rotated clockwise (so the left side is top, right side is bottom)

**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** latest

**Last working release (if known):** never worked correctly on mobile - only on desktop 

**Browser and Operating System:** installed/running on Raspberry Pi 5

 Android 14 on Samsung S23 Ultra, Chrome latest Version

**Description of problem:**

 Sankey Chart Card on Home Assistant works great on desktop browser view - but when opening the very same on my mobile - no matter if directly in mobile browser or the native HA app - it always will be displayed 90° rotated clockwise (so the left side is top, right side is bottom)
![Desktop-Screenshot of Sankey-Chart card](https://github.com/MindFreeze/ha-sankey-chart/assets/35795055/9581711d-1620-480f-b92e-39e56e019533)
![Mobile-Screenshot of Sankey Chart card](https://github.com/MindFreeze/ha-sankey-chart/assets/35795055/4ae67c9a-b740-4c30-9524-62c8d7bcc8ee)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by MindFreeze** [comment]
This is a feature, not a bug 😉
Use the `layout` option to lock it if you want

**Comment by HQOFIQ** [comment]
Thank you - got it!
