### ISSUE TITLE
Hide remaining ?

### ISSUE THREAD

**Issue by realjax** [MindFreeze/ha-sankey-chart#208]
Every few seconds I  get this 
![Screenshot 2024-06-26 at 09 50 09](https://github.com/MindFreeze/ha-sankey-chart/assets/883435/bfedee68-6de8-43de-a31a-b53d7b7b6466)

Note the veeeeeeeery small remaining child value( yellow near bottom) 
Which only exist for a second or two untill the state of the parents is corrected again.

Is there a way to permanently hide that remaining child?

**Comment by MindFreeze** [comment]
You can set the `min_state` option to hide small values

**Comment by realjax** [comment]
sorry, I missed that in the docs, Thanks!
