### ISSUE TITLE
Render errormessage on error instead of nothing

### ISSUE THREAD

**Issue by mvdwetering** [MindFreeze/ha-sankey-chart#21]
**Is your feature request related to a problem? Please describe.**
I noticed that the card was not showing up anymore, just empty space. Turns out this was due to me renaming some entities, which made the configuration invalid. It is understandable that it fails to render in this case, but it would have been nice to have an error message to get an indication something is wrong in the configuration.

**Describe the solution you'd like**
Render an error message when failing to render the card.

**Describe alternatives you've considered**
Not really an alternative, but now I looked at the JS console and remembered I just changed some entity names.

**Additional context**
No other context.

**Comment by MindFreeze** [comment]
fixed in v0.8.0
