### ISSUE TITLE
Conversion UoM: "m3" -> "l" not change values

### ISSUE THREAD

**Issue by kzajac83** [MindFreeze/ha-sankey-chart#217]
Hello

In my cause UoM "m3" and without unit conversion is displayed as below:
![image](https://github.com/user-attachments/assets/48cafebb-0ffd-4596-b854-3617a1688df8)

After conversion m3 to liters change UoM but values no changes. In this cause should multiplied by1000. 
![image](https://github.com/user-attachments/assets/626b5e2d-2c8c-4acf-a31e-b94d504b8b41)

**Comment by MindFreeze** [comment]
`convert_units_to` is not a general conversion option. It's supported values are explicitly listed in the README. General unit conversion can be done in the entity settings in HA
