### ISSUE TITLE
Manage total_increasing energy sensor

### ISSUE THREAD

**Issue by lahayeg** [MindFreeze/ha-sankey-chart#22]
**Is your feature request related to a problem? Please describe.**
I managed energy consumption with different sensors which value is increasing, no daily reset. This works fine with Energy dashboard but not with the card.

**Describe the solution you'd like**
By able to manage delta of the value between to time that could be defined. Remaining could highlight rest of energy not identified (I don't have smartplug everywhere)

**Describe alternatives you've considered**
Create for each sensor a related utiliy_meter sensor but it's like duplicate data, which I don't like

**Comment by MindFreeze** [comment]
This is not something that can be done in cards currently. HA only provides latest state to cards and doesn't have any documentation on how their energy cards work.

This card also aims to be more generic. I use it mainly for power, not energy. Other people use it to show other tree like data. Coupling it to energy would hurt the other use cases.
