### ISSUE TITLE
Add Today as an option

### ISSUE THREAD

**Issue by blacknell** [MindFreeze/ha-sankey-chart#225]
**Is your feature request related to a problem? Please describe.**
On my wall tablet home screens I want my family to realise what energy has been used today and where. I find they don't click on the date to select today and in the morning it's still showing (what is now) yesterday. On this family page having a date selector is messy IMO.

**Describe the solution you'd like**
An option to set the date range to today (0000-2359) which behaves as if I'd set the date selector

**Describe alternatives you've considered**
Obviously users can choose the date selector.

**Additional context**

**Comment by AleXSR700** [comment]
Which entities are you tracking? Are they not e.g. `ENERGY Today`? So each day they are automatically showing "Today"?

**Comment by blacknell** [comment]
I'm using Energy Total entities. I was under the impression that the sankey chart works out energy for a date in the same way as energy dashboard does - get start and end of the period and display that.

Are you saying that using Energy Today entities, it would effectively ignore the date selector?

**Comment by AleXSR700** [comment]
No, I am saying that if you use energy today and you do not manually set the date selector, it will always show the consumption of the current day (so far).

I have not tried how Sankey processes Energy Total. If you do not select a date, does it show the total (of all days) or does it show Energy today?
 If the latter and if you always want to show the current day to your family, can you not just leave the date selector at default (today)?

And if it shows the actual total, then if you track Energy Today instead and leave the date selector at default, it will always show the today's consumption without you clicking anything.

**Comment by blacknell** [comment]
With total, it works and display the delta for the selected day. 

For today, I think it will go back and retrieve the historical values for the selected day and show the same results. 

It worth an experiment.

**Comment by MindFreeze** [comment]
You can just hide the date selector. It default to today anyway

**Comment by blacknell** [comment]
It does but the next morning will it have refreshed? I think not as this is what drive me to ask. If you navigate away or refresh then sure but on a wall tablet it should always show current day.

**Comment by AleXSR700** [comment]
Never tested if the date selector resets at midnight... interesting...Need to test that.

But two options here then:
- hide the date selector so it always stay at default (at least in the "public" dashboards shown on your family tablet
- write an automation that sets the date selector to "today" every day at midnight

**Comment by MindFreeze** [comment]
I have automations to turn off my tablet dashboard when no one is in the room/house or we are sleeping. No point eating energy. 
But if you prefer to keep it always on, you can just refresh the whole page after midnight with BrowserMod or some navigate actions in walllpanel/fully kiosk...

**Comment by MindFreeze** [comment]
Just realised this issue is a subset of #151, so I will close it as a duplicate.

**Comment by blacknell** [comment]
This was closed as `not planned` rather than `duplicate`

That said it was fixed in [v3.3.0](https://github.com/MindFreeze/ha-sankey-chart/releases/tag/v3.3.0) - fantastic
