### ISSUE TITLE
Support `energy_date_selection: true` also for Power sensors

### ISSUE THREAD

**Issue by AleXSR700** [MindFreeze/ha-sankey-chart#226]
**Is your feature request related to a problem? Please describe.**
At the moment the user can use the `energy_date_selection: true` to display different time periods, but only for integral sensors, e.g. `energy_today`.

**Describe the solution you'd like**
Support `energy_date_selection: true` also for "live" power sensors like `energy_power`.

**Describe alternatives you've considered**

**Additional context**

**Comment by MindFreeze** [comment]
This makes no sense. Power instantaneous. Energy is accumulated.

**Comment by AleXSR700** [comment]
But Power has a history too. You can follow the energy power and create the same kind of chart as for energy today.

So you can see what the consumption was for a given time or a given range.

**Comment by MindFreeze** [comment]
Power is not accumulated. It would have to be min, max or mean of the power for the day and that is not useful at all. Min, max or mean occur at different times for each sensor, so there is no relation to display in the chart.

**Comment by AleXSR700** [comment]
I was thinking of showing the current value. But I see your point about it not being too useful. At least not for too many users.

My idea was to select date and time and see the power values of that time.

Essentially, if you do not select date and time, you see the current consumption in watts. That is useful because it shows who is currently consuming what in real time.

I find it interesting to see which consumer is consuming what at which time. As the Energy Power sensor is real time and Energy Today only updates far less frequently, analysing which consumer was being wastefull is less precise.

But again, I see your point and the limited (maybe even to me ^^ ) user group.

**Comment by MindFreeze** [comment]
HA doesn't even have such precise historical data. Even if it is not purged from the recorder, it would be compressed to the min, max and mean values for each hour.
