### ISSUE TITLE
Set height size in percent

### ISSUE THREAD

**Issue by palitu** [MindFreeze/ha-sankey-chart#23]
**Is your feature request related to a problem? Please describe.**
There are issues using it on mobile, where the screen height is different.

**Describe the solution you'd like**
the diagram will scale vertically depending on the size of the screen

**Describe alternatives you've considered**
Instead of using absolute pixel size, it would be nice to have a percent.  allow for either absolute or relative heights in the configuration.

**Additional context**

**Comment by MindFreeze** [comment]
I don't understand the problem. I use it on mobile without any issues except that it is designed to be wider and not taller due the way data is displayed.
HA wants height in pixels and doesn't care about screen height. Layout is not managed by the cards. It is managed by https://developers.home-assistant.io/docs/frontend/custom-ui/custom-view .
Moreover a specific total height of the card is needed for all the size calculations within. I've tried using % and it is problematic.

There might be something similar to [this](https://github.com/thomasloven/lovelace-layout-card), that would allow you to change the mobile layout somehow.

**Comment by MindFreeze** [comment]
I don't know of any card that changes its height according to the screen and AFAIK that would mess up the layout of other cards.

**Comment by bjiirn** [comment]
I was looking for the same thing.
This would make sense for "Panel View" where you only have one card that fills the entire dashboard.
