### ISSUE TITLE
Default sort order is reversed and can't be changed

### ISSUE THREAD

**Issue by Cougar** [MindFreeze/ha-sankey-chart#247]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
3.5.0
**Last working release (if known):**
-
**Browser and Operating System:**
Linux Firefox

**Description of problem:**
Documentation states that only valid `sort_by` option is `state` which is not a default sorting. Default is an entities order in configuration/YAML (doc: "Note that the order of this list matters").

Problem is that this default order of entities in graph is in reverse. `sort_dir` doesn't work either (it works only with `sort_by: state`).

Here is the screenshot with three states in order "A, C, B" that are shown in reverse order "B, C, A" in chart:

![Screenshot 2024-12-08 at 20-44-38 S21 5G – Home Assistant](https://github.com/user-attachments/assets/2395a454-063f-4ffe-ab49-82ebdbf88f2b)

I deliberately ordered names and entities so that it is well visible that sorting is based on config order and not based on name, entity id or state (value).

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

It is probably because in function `sortBoxes` the sorting has been done only in case of `sort === 'state'` and not otherwise. I'm not sure if `sort_dir` option would be useful at all without `sort_by: state` but the order should be fixed nevertheless IMHO.

I don't know where this reversal happens but one way to fix it is inside [`sortBoxes()`](https://github.com/MindFreeze/ha-sankey-chart/blob/10d85b0ffef73cf5994f3e297c9892e7aa4d01b2/src/utils.ts#L194) function
```diff
diff --git a/src/utils.ts b/src/utils.ts
index 2cb63a8..8491a48 100644
--- a/src/utils.ts
+++ b/src/utils.ts
@@ -214,6 +214,8 @@ export function sortBoxes(parentBoxes: Box[], boxes: Box[], sort?: string, dir =
     } else {
       boxes.sort((a, b) => sortByParent(a, b, (a, b) => (a.state < b.state ? -1 : a.state > b.state ? 1 : 0)));
     }
+  } else {
+    boxes.reverse();
   }
   return boxes;
 }
```
Of course it would be better to find a real cause and fix it properly. Thoughts?

**Comment by MindFreeze** [comment]
The real issue here is #234 . I will probably fix it in v4
I'll close this as a duplicate
