### ISSUE TITLE
Ok to use for real-time statistics?

### ISSUE THREAD

**Issue by markusschloesser** [MindFreeze/ha-sankey-chart#25]
I just implemented your really great card to show real-time Power Usage and it works great! So thank you!
But that got me thinking: Is it ok to use it for that? Or am I gonna end with a messed up system? Pretty new to HA
<img width="347" alt="image" src="https://user-images.githubusercontent.com/59286549/173713507-9b525eda-9c0a-4bfc-b51a-11bbcefa76d3.png">
Or would it be better to wait for the throttling feature?

**Comment by MindFreeze** [comment]
This is exactly what I use it for. You are good.

**Comment by markusschloesser** [comment]
Great, thanks! 😊
