### ISSUE TITLE
Allow vertical alignment for entity name and value

### ISSUE THREAD

**Issue by Nooton92** [MindFreeze/ha-sankey-chart#251]
I am trying to make a chart that is easily viewable from a smart phone. I can easily get three sections to fit a horizontal chart but the names for each entity get cut off in section 1 and 2.

**Describe the solution you'd like**
I would like to be able to configure each entity to either horizontal or vertical alignment much like the layout option on a mushroom entity card. This will allow for more characters before they get cut off on small screens.
ex.   1.2 kW     vs.     1.2 kW Imported
       Imported

**Describe alternatives you've considered**
Possibly set the alignment by section instead of each entity.

**Additional context**
Example from a mushroom entity card:
<img width="520" alt="image" src="https://github.com/user-attachments/assets/c7d08893-3a76-4b1d-9da3-5e0fa83ea8f2" />
Example of text that is cut off that would be solved with this issue:
![1000002485](https://github.com/user-attachments/assets/2081b43d-b06e-4f1d-8d1f-d48d169c7a27)

**Comment by MindFreeze** [comment]
You should use the layout option. Making horizontal layout fit a phone is pointless

**Comment by Nooton92** [comment]
Switching the layout to vertical cuts off all the names of the last section which is arguably the most important section to have fully visible.

I use the chart for instantaneous power and has been very useful for tracking down items that use more energy in standby than I thought.

**Comment by MindFreeze** [comment]
> Switching the layout to vertical cuts off all the names of the last section

It shouldn't. Are you using a `sections` with a fixed `rows` option or something? The card doesn't cut off the labels on its own.

**Comment by Nooton92** [comment]
No fixed sections everything is set to sort by ascending. If I switch to vertical layout the third section is not readable which is why I am currently using horizontal as for my use it is the most valuable piece of information.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MindFreeze** [comment]
There must be something specific about your setup. The card is dynamically sized in vertical mode specifically to display all labels. Perhaps try it on new dashboard with the default theme
