### ISSUE TITLE
Remaining object location to be configurable

### ISSUE THREAD

**Issue by Masterz69** [MindFreeze/ha-sankey-chart#28]
No problem.
Some time nice to have "Remaining object" located on top, not bottom.
Thank You very much.

**Comment by MindFreeze** [comment]
I have this planned for v1.0.0 because it will probably be a breaking change

**Comment by flopp999** [comment]
@Masterz69

Do you mean that you don't want it to be equally distributed?
Because I want to have "influx_poolheat" just below "influx_pool".
![image](https://user-images.githubusercontent.com/21694965/187080648-8a559314-f493-49d8-83ae-c87eb2bbb304.png)

**Comment by MindFreeze** [comment]
added in v1.0.0
