### ISSUE TITLE
Version displayed in console does not match HACS version

### ISSUE THREAD

**Issue by mvdwetering** [MindFreeze/ha-sankey-chart#32]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

0.10.0

**Last working release (if known):**

don't know

**Browser and Operating System:**

Windows 10, Chrome

**Description of problem:**

I had the devtools console open and noticed the version for this card does not match the version displayed in HACS.
According to HACS I have 0.10.0, but the console shows version 1.4.1

![image](https://user-images.githubusercontent.com/732514/183240716-86f23bd8-e173-4e9f-9fea-3fd151cf31ab.png)

**Javascript errors shown in the web inspector (if applicable):**

Probably unrelated, but this warning shows for the ha-sankey-chart.js in the console
```
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
```

**Additional information:**

**Comment by MindFreeze** [comment]
Lol, totally forgot avout that. Thanks
