### ISSUE TITLE
Wide option didn't effect

### ISSUE THREAD

**Issue by abu9** [MindFreeze/ha-sankey-chart#35]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** v0.11.0

**Last working release (if known):**

**Browser and Operating System:** Chrome Version 104.0.5112.101 @win10 / HA official client @iOS 15.4.1

**Description of problem:**
Wide option didn't effect,  empty space still in the right side (purple area).
 ![https://imgur.com/a/jmTBOWD](https://i.imgur.com/K0sLnIf.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by MindFreeze** [comment]
@abu9 Is this issue still present in the latest version?

**Comment by MindFreeze** [comment]
closing as stale
