### ISSUE TITLE
Missing flow

### ISSUE THREAD

**Issue by flopp999** [MindFreeze/ha-sankey-chart#36]
- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
0.11.0
**Browser and Operating System:**
Windows 11, Edge, Chrome

**Description of problem:**
missing "flow" to last entity

![image](https://user-images.githubusercontent.com/21694965/187071283-c5d7103f-58dc-4694-864a-9f60cfcfeb3b.png)

**Comment by flopp999** [comment]
I think I found the problem.

If I summaries all the items to the right it is more than 5610, so I need to check my templates for the sensor

**Comment by MindFreeze** [comment]
I have been planning to do something about this for a while. Just created a ticket to formalize the idea. #37
