### ISSUE TITLE
Ability to highlight the connectors related to the entity under the mouse cursor

### ISSUE THREAD

**Issue by Madelena** [MindFreeze/ha-sankey-chart#39]
When I mouseover an entity, it will be nice to see the paths connected to its parent and children in a brighter color. This will be useful for charts with lots of entities with low values, which make it hard to see what its parents and children are.

A second iteration of this feature would be the ability to highlight not just the parent and children, but also its grandparents and grandchildren, so that we can trace what affects the entity and what the entity affects all the way down the line.

For example, mouseover on my Fridge entity will highlight the following:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/4341881/188279741-a65929c7-2b79-4a77-8d23-7674666d4009.png">

**Comment by MindFreeze** [comment]
Good idea

**Comment by MindFreeze** [comment]
added in v1.1.0
