### ISSUE TITLE
Text overlaps when boxes are too short

### ISSUE THREAD

**Issue by Madelena** [MindFreeze/ha-sankey-chart#4]
**Release with the issue:** v0.3.2

**Description of problem:**

When the value of a box is too low, there is not enough space to display the text, causing them to overlap with each other. Perhaps there should be an option to hide text if box height is less than a certain value?

(Thanks a lot again for the add-on! Sorry for sending so many issues in 😅)

**Comment by MindFreeze** [comment]
I don't like hiding the text because you won't know what you are looking at unless it has a unique color. Might experiment with reducing font size or making that a config option.

Otherwise this behavior can be tweaked even now with min_box_height and min_box_distance options.

**Comment by Madelena** [comment]
Maybe tooltip on mouseover? Smaller fonts for smaller items would work too.

**Comment by MindFreeze** [comment]
Tooltip is a great idea in general. I use this on a read only mounted dashboard and haven't considered mouse actions much but it makes sense.

**Comment by MindFreeze** [comment]
fixed in v0.4.1
