### ISSUE TITLE
Minimal Font Size

### ISSUE THREAD

**Issue by judzk** [MindFreeze/ha-sankey-chart#42]
**Is your feature request related to a problem? Please describe.**
Hi, it's possible to set the minimal font size? 
I love your Sankey Graph, but i can't read everything

**Describe the solution you'd like**
Set minimal font size or a custom parameter in each entity
**Additional context**
<img width="355" alt="image" src="https://user-images.githubusercontent.com/26792639/190429118-1e5e82dd-1920-43d2-97ef-055a2b1dd598.png">

**Comment by MindFreeze** [comment]
Setting it per entity is a no go and could cause rendering issues. But the example here is def a bug. There is a lot of room below to expand the font so it should handle this case better.

**Comment by judzk** [comment]
I added a second sensor and now it's ok. Seem like the bug only appear with one sensor

**Comment by chrismaddahl** [comment]
The problem seems to be still there:

![Image](https://github.com/user-attachments/assets/69605c77-b425-413d-b46f-d2eeb277ee77)

**Comment by MindFreeze** [comment]
> The problem seems to be still there:
> 
> ![Image](https://github.com/user-attachments/assets/69605c77-b425-413d-b46f-d2eeb277ee77)

I don't see the issue in your image.
Btw the font size is determined by the available space, so you can increase the minimum size by increasing `min_box_size` and/or `min_box_distance`
