### ISSUE TITLE
Add space between number and unit

### ISSUE THREAD

**Issue by klaus1k** [MindFreeze/ha-sankey-chart#43]
Hey,

first of all - awesome card! Just found it yesterday and already in love with it!

One little thing would make it perfect for me - could you add a space between the numbers and the units? Would be cleaner to read for me, e.g. "1287 kWh" instead of "1287kWh".

Kind regards,
Klaus

**Comment by MindFreeze** [comment]
Thanks!
You can do this with card-mod. See #14
I can't make everyone happy so when card-mod can handle it, I will rely on that.

**Comment by klaus1k** [comment]
Thanks for the quick reply, will do it with card-mod!
Sorry, somehow overlooked #14 before posting the issue.
