### ISSUE TITLE
Sankey flow not rendering correctly?

### ISSUE THREAD

**Issue by brynyneuadd** [MindFreeze/ha-sankey-chart#44]
I'm sure it's me, but trying to do the simplest sankey flow and it's just not rendering correctly. Following the examples to the letter as far as I can see, but the Grid import isn't linking to the consumption sensor.

It's possible it's a bug, but almost certainly something I'm not grasping!

![Capture](https://user-images.githubusercontent.com/106859705/192111814-d3d477f2-5de1-4dbc-b633-04bdeb2c316a.JPG)

**Comment by MindFreeze** [comment]
You have a sensor problem. Your consumption doesn't seem to include grid import. PV and Battery are already more than 36.1
