### ISSUE TITLE
Negative values are not handled properly

### ISSUE THREAD

**Issue by MindFreeze** [MindFreeze/ha-sankey-chart#50]
We need a `Math.abs()` somewhere

**Comment by na4ma4** [comment]
In your comment you said `Math.abs()`, but ended up using `Math.max(0, value)` to set negative to zero.

What was the rationale for that ?

It would also be good if 0 values could be displayed (if `min_state` could be set to negative numbers).

**Comment by MindFreeze** [comment]
Abs doesn't make sense in many cases because negative values mean something else and they shouldn't be converted to positive.
Displaying zeros is tricky because then I have to handle division by 0 in many places. And it wouldn't make sense in the UI any way
