### ISSUE TITLE
Component overwrites global hass state

### ISSUE THREAD

**Issue by elupus** [MindFreeze/ha-sankey-chart#56]
**Checklist:**

- [x] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

The component overwrites global hass object state cause wrong values to be displayed in all dialogs.

I think this lone is the (or one of) culprit.
https://github.com/MindFreeze/ha-sankey-chart/blob/5e64f26943f4984752051b92689323c3a0fbd616/src/ha-sankey-chart.ts#L77

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by MindFreeze** [comment]
Good catch. Fixed in v1.3.2
