### ISSUE TITLE
Make section width configurable

### ISSUE THREAD

**Issue by bastiaanterhorst** [MindFreeze/ha-sankey-chart#62]
**Is your feature request related to a problem? Please describe.**
Currently sections are evenly divided over the available width. This doesn't always produce the best results, because some sections need more space than others.

**Describe the solution you'd like**
I would like sections to get a `width` property where width can be configured as a percentage.

**Describe alternatives you've considered**
I do not this there is another way to achieve this.

**Comment by MindFreeze** [comment]
added in v1.11.0
