### ISSUE TITLE
Custom element doesn't exist: sankey-chart

### ISSUE THREAD

**Issue by fusion94** [MindFreeze/ha-sankey-chart#81]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.9.0

**Last working release (if known):**
1.8.2

**Browser and Operating System:**
Chrome and Safari on MacOS

**Description of problem:**
Upgraded to 1.9.0 and now see this. 

`Custom element doesn't exist: sankey-chart`

Downgrading to 1.8.2 fixed the issue

**Additional information:**

**Comment by screem20056** [comment]
same issue here even downgrading to 1.8.2 needs a full restart of the RPi to work

**Comment by MindFreeze** [comment]
fixed but cache seems to be very aggressive so it can take some time for the changes to take effect
