### ISSUE TITLE
ignoring entities with value below a threshold

### ISSUE THREAD

**Issue by f-zappa** [MindFreeze/ha-sankey-chart#87]
I recently installed a metering plug at my dishwasher and realized that it still consumes 0.07W when powered off (stupid thing). This doesn't look nice in my sankey chart:
![image](https://user-images.githubusercontent.com/43571251/214047406-229c9af2-cfca-4f64-b2b9-73bb26a351d0.png)
I think for this kind of diagram simplicity is more important than 100% accuracy. It would be perfect to have a "threshold" setting (per entity) and the card would ignore an entity if the value is below the threshold.

**Comment by MindFreeze** [comment]
Having this per entity seems to niche. It makes sense to set this for this entire card. 
Generally entity specific things are better handled within HA with templates. I've made exceptions when there is a lot of demand but want to avoid it.

**Comment by f-zappa** [comment]
Well, I could also live with having this for the entire card 😎
