### ISSUE TITLE
Connections accross sections

### ISSUE THREAD

**Issue by MindFreeze** [MindFreeze/ha-sankey-chart#9]
Or ability to skip a section. Could be implemented with ghost boxes in between.

Also mentioned in #6

**Comment by Muppetteer** [comment]
I've been waiting for this one but cannot work out how to do it. I am currently fudging it with the dirty hack of including an entity twice in different sections and making it a child of itself. If I remove the intermediary entity I now get an orphan entity that is not connected to anything.

Is there something I need to put in between to achieve the "passthrough" I can see in the code? Could you update the docs with an example? Thanks

**Comment by MindFreeze** [comment]
This is exactly how it works. I just adds child entities in the intermediary sections to connect the curve. The 'passthrough' type enables special rendering for those. Same rules about state apply though. You can try to keep your intermediary entities and just add `type: passthrough` to them. This would even allow you to position them manually.

I haven't had time to properly explain this in the README.

Here is a screenshot of a weird test I have
![192 168 1 100_8123_lovelace-test_0](https://user-images.githubusercontent.com/5219205/183995865-94d7b021-0482-443e-b4a4-2a85c14c6854.png)

**Comment by Muppetteer** [comment]
Thanks, it is working now. I suspect it may have been a browser cache issue not picking up the new code. I found that keeping the entity, setting `type: passthrough` and connecting to itself as a child works best as I can control the order and colour of the branches.

**Comment by MindFreeze** [comment]
Updated README

**Comment by icefest** [comment]
Is it just me or does the combination of child/parent state not work with passthrough?

**Comment by MindFreeze** [comment]
@icefest It should. I've used it with passthrough before. Maybe there is some sort of regression. Feel free to open a bug report
