### ISSUE TITLE
Should be scrollable if chart does not fit in the view

### ISSUE THREAD

**Issue by Floppe** [MindFreeze/ha-sankey-chart#91]
A huge thank you for this amazing component. I really love it.

**Checklist:**

- [* ] I updated to the latest version available
- [* ] I cleared the cache of my browser

**Release with the issue:**
v1.9.3

**Last working release (if known):**

**Browser and Operating System:**
Windows 10 and Chrome 109 with large monitors -> OK
Android 11 and Chrome with small screen and portrait orientation -> not so good

**Description of problem:**
Some days ago I added another section so I get energy consumption per room in my house also. That's when it started to become more difficult to see sensors in my mobile.

When sankey charts have 4 or more sections, then the width will grow beyond my mobile phones capabilities in portrait orientation. This makes all other components in that view wider and difficult to look at.

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**
Perhaps not a bug per see, but I believe all components should handle these basic things so filing it as a bug. Maybe related to #86. I have fiddled with the wide option without success.

So better would be that the entire component becomes scrollable when it does not fit in the view.

Also, I'm using the view type grid everywhere.

**Comment by MindFreeze** [comment]
I am aware of this and am thinking about it but am not sure if scrolling is the solution yet. I've also been thinking about a vertical layout for mobile but that would be a huge change.
For now I just turn my phone horizontally :/

**Comment by MindFreeze** [comment]
You can now set minimum width per section. If the screen width is less than the sum of min width of all sections. The card will extend beyond the screen and be scrollable

**Comment by Floppe** [comment]
Ah, got it. Thanks, it works.
