### ISSUE TITLE
Make throttle time kick in only after the chart is first drawn

### ISSUE THREAD

**Issue by RoSche2001** [MindFreeze/ha-sankey-chart#93]
Use case: Energy sankey charts do not need a lot of updating. In order to decrease the system load it might be good to use the throttle time to reduce the updating. Currently however, the throttle time is already used before the first rendering. It means when you set throttle to e.g. 30 minutes you will not see a chart before those 30 minutes have gone by.

Proposal: Make the throttle time to only kick in after the sankey chart is rendered for the first time. 
This will draw immediately the chart but subsequent updates can be set to a much longer time.

**Comment by MindFreeze** [comment]
Did know it did that. That's a bug

**Comment by RoSche2001** [comment]
Many thanks. I updated to the version where you have fixed it.
It works well on first draw.

However, when in change the time period used for the energy meters and the chart shall be drawn again with the new time period, it still uses the throttle time until it does something. Could you maybe look into counting every redraw based on a different time period choosen like a new draw at first view.
If the chart would behave like proposed then one could set a long throttle for such energy charts and it would only need to be redrawn at first view and at the change of the time period.
Many thanks.

**Comment by MindFreeze** [comment]
Alright. Makes sense.
