### ISSUE TITLE
Support total state_class for daily energy resets like the HA Energy Dashboard

### ISSUE THREAD

**Issue by GitHubGoody** [MindFreeze/ha-sankey-chart#94]
I would have started this as a discussion, but that section isn't enabled on this repo.

I recently got most of my house's power and energy in HA thanks to an Emporia Vue, Powercalc, templates, and the new sensor groups. With those all set up, configuring my energy Sankey chart was pretty straightforward. Thank you!

But, I noticed that the energy totals for my mostly Powercalc'd light group was taking up most of my total energy demand. Something wasn't right.

The power curves I configured for each of the lights was working and accurately tracking each light's power state with the measurement state_class, but the energy entity's state_class (total) seemed to not reset to 0 each night in Sankey although it did in the HA Energy Dashboard.

Does the Sankey card need the state class to be total_increasing for an energy sensor that does not reset daily on its own? How does the HA Energy Dashboard do it?

**Describe the solution you'd like**
The Sankey card to work like the HA Energy Dashboard allowing for energy entities which do not reset daily.

**Describe alternatives you've considered**
I think I would need to create ~30 daily utility sensors so the state will reset each night.

**Additional context**
Powercalc-created energy sensor for one of the lights:
![image](https://user-images.githubusercontent.com/46235745/218872765-d9db0917-11a5-4c7d-9cb5-a7dd218cdee7.jpeg)

A daily utility sensor based on that same entity:
![image](https://user-images.githubusercontent.com/46235745/218872872-451a6cd5-3032-4476-8616-702a6bda3aa9.jpeg)

The same entities next to each other showing approximately the same used energy for the day despite the total running value being much different:

![image](https://user-images.githubusercontent.com/46235745/218873486-60e1e1da-8825-4cca-a9bb-a4a879accca2.jpeg)

**Comment by MindFreeze** [comment]
So you use energy_date_selection? Because that doesn't need a reset and works exactly like the energy dashboard.

**Comment by GitHubGoody** [comment]
Ah, I swear I read the entire repo, but didn't realize the date-selector was necessary for this sort of thing. I was trying to put the Sankey chart in a panel to keep the view clean. So, I just had to modify the width to fill with layout-card and vertical-stack the date-selector. 

Thanks. It seems to be working as expected now.

Is there any reason to not have whatever the date-selector feeds into in the Sankey card's code just default to today's date when the date-selector is not present on the view?

**Comment by MindFreeze** [comment]
The reason is that this card is not created for daily energy, it has other uses. I originally created it to view current power draw and this is still my main use for it. Others use it to break down values like costs/budget.
